<?php

// Vídeos da revisão do Hugo, aprovados por tira de frames e **INSTALADOS em
// 17/09/2026**: subiram pro R2 por cima dos antigos (mesmo slug, mesma URL), e
// por isso entraram em produção na hora, sem deploy. Os .mp4 seguem em
// storage/app/private/higgsfield/aprovados-revisao-hugo/<numero>.mp4 como
// registro de qual lote gerou cada um.
//
// Conferido depois de subir: os 57 objetos no R2 batem byte a byte com o
// arquivo local, e o poster .jpg de cada um foi regerado.
//
// PRA DESFAZER: os vídeos que estavam no ar foram baixados antes em
// public/uploads/_backup-antes-revisao-hugo/<slug>.mp4 (57 arquivos, 67 MB,
// fora do git). Basta copiar de volta pra public/uploads/exercise-demos/,
// apontar o video_url pro caminho local e rodar publicar-demonstracoes.
//
// O NÚMERO é o #N da tela de vídeos na biblioteca de 663 (pós-poda de 08/09).
// Ele NÃO é estável: se a poda dos 147 rodar, tudo se desloca. O nome é a
// chave confiável.
return [
    7 => ['nome' => 'Crucifixo declinado com halteres', 'grupo' => 'Peito', 'arquivo' => '7.mp4'],
    8 => ['nome' => 'Crucifixo inclinado com halteres', 'grupo' => 'Peito', 'arquivo' => '8.mp4'],
    11 => ['nome' => 'Crucifixo reto', 'grupo' => 'Peito', 'arquivo' => '11.mp4'],
    14 => ['nome' => 'Flexão de braço', 'grupo' => 'Peito', 'arquivo' => '14.mp4'],
    36 => ['nome' => 'Supino declinado com halteres', 'grupo' => 'Peito', 'arquivo' => '36.mp4'],
    45 => ['nome' => 'Supino máquina', 'grupo' => 'Peito', 'arquivo' => '45.mp4'],
    56 => ['nome' => 'Barra fixa pegada supinada (chin-up)', 'grupo' => 'Costas', 'arquivo' => '56.mp4'],
    59 => ['nome' => 'Extensão lombar na máquina', 'grupo' => 'Costas', 'arquivo' => '59.mp4'],
    64 => ['nome' => 'Levantamento terra com halteres', 'grupo' => 'Costas', 'arquivo' => '64.mp4'],
    90 => ['nome' => 'Remada curvada com halteres', 'grupo' => 'Costas', 'arquivo' => '90.mp4'],
    94 => ['nome' => 'Remada máquina', 'grupo' => 'Costas', 'arquivo' => '94.mp4'],
    115 => ['nome' => 'Desenvolvimento na máquina', 'grupo' => 'Ombros', 'arquivo' => '115.mp4'],
    149 => ['nome' => 'Rosca com corda na polia baixa', 'grupo' => 'Bíceps', 'arquivo' => '149.mp4'],
    153 => ['nome' => 'Rosca de bíceps sentado com halteres', 'grupo' => 'Bíceps', 'arquivo' => '153.mp4'],
    158 => ['nome' => 'Rosca direta na polia', 'grupo' => 'Bíceps', 'arquivo' => '158.mp4'],
    161 => ['nome' => 'Rosca invertida na polia', 'grupo' => 'Bíceps', 'arquivo' => '161.mp4'],
    162 => ['nome' => 'Rosca martelo', 'grupo' => 'Bíceps', 'arquivo' => '162.mp4'],
    163 => ['nome' => 'Rosca martelo alternada', 'grupo' => 'Bíceps', 'arquivo' => '163.mp4'],
    168 => ['nome' => 'Rosca Scott com halter unilateral', 'grupo' => 'Bíceps', 'arquivo' => '168.mp4'],
    173 => ['nome' => 'Extensão de tríceps na máquina', 'grupo' => 'Tríceps', 'arquivo' => '173.mp4'],
    176 => ['nome' => 'Flexão diamante para tríceps', 'grupo' => 'Tríceps', 'arquivo' => '176.mp4'],
    177 => ['nome' => 'Mergulho entre bancos', 'grupo' => 'Tríceps', 'arquivo' => '177.mp4'],
    180 => ['nome' => 'Mergulho no banco', 'grupo' => 'Tríceps', 'arquivo' => '180.mp4'],
    184 => ['nome' => 'Tríceps coice com halter', 'grupo' => 'Tríceps', 'arquivo' => '184.mp4'],
    185 => ['nome' => 'Tríceps coice na polia', 'grupo' => 'Tríceps', 'arquivo' => '185.mp4'],
    186 => ['nome' => 'Tríceps corda', 'grupo' => 'Tríceps', 'arquivo' => '186.mp4'],
    189 => ['nome' => 'Tríceps francês na polia', 'grupo' => 'Tríceps', 'arquivo' => '189.mp4'],
    190 => ['nome' => 'Tríceps francês sentado com halter', 'grupo' => 'Tríceps', 'arquivo' => '190.mp4'],
    193 => ['nome' => 'Tríceps na polia com barra V', 'grupo' => 'Tríceps', 'arquivo' => '193.mp4'],
    194 => ['nome' => 'Tríceps na polia com pegada cruzada', 'grupo' => 'Tríceps', 'arquivo' => '194.mp4'],
    195 => ['nome' => 'Tríceps na polia pegada supinada', 'grupo' => 'Tríceps', 'arquivo' => '195.mp4'],
    197 => ['nome' => 'Tríceps pulley barra reta', 'grupo' => 'Tríceps', 'arquivo' => '197.mp4'],
    235 => ['nome' => 'Agachamento com peso corporal', 'grupo' => 'Pernas', 'arquivo' => '235.mp4'],
    246 => ['nome' => 'Agachamento sissy', 'grupo' => 'Pernas', 'arquivo' => '246.mp4'],
    254 => ['nome' => 'Cadeira extensora unilateral', 'grupo' => 'Pernas', 'arquivo' => '254.mp4'],
    276 => ['nome' => 'Elevação pélvica com perna estendida', 'grupo' => 'Posterior', 'arquivo' => '276.mp4'],
    280 => ['nome' => 'Flexora em pé na máquina', 'grupo' => 'Posterior', 'arquivo' => '280.mp4'],
    288 => ['nome' => 'Mesa flexora', 'grupo' => 'Posterior', 'arquivo' => '288.mp4'],
    318 => ['nome' => 'Elevação de quadril na máquina', 'grupo' => 'Glúteos', 'arquivo' => '318.mp4'],
    320 => ['nome' => 'Elevação de quadril unilateral', 'grupo' => 'Glúteos', 'arquivo' => '320.mp4'],
    329 => ['nome' => 'Ponte de glúteo no solo', 'grupo' => 'Glúteos', 'arquivo' => '329.mp4'],
    337 => ['nome' => 'Panturrilha em pé no step', 'grupo' => 'Panturrilha', 'arquivo' => '337.mp4'],
    346 => ['nome' => 'Abdominal bicicleta', 'grupo' => 'Core', 'arquivo' => '346.mp4'],
    350 => ['nome' => 'Abdominal na máquina com carga', 'grupo' => 'Core', 'arquivo' => '350.mp4'],
    354 => ['nome' => 'Abdominal remador', 'grupo' => 'Core', 'arquivo' => '354.mp4'],
    360 => ['nome' => 'Dragon flag', 'grupo' => 'Core', 'arquivo' => '360.mp4'],
    361 => ['nome' => 'Elevação de joelhos suspenso', 'grupo' => 'Core', 'arquivo' => '361.mp4'],
    363 => ['nome' => 'Elevação de pernas suspenso na barra', 'grupo' => 'Core', 'arquivo' => '363.mp4'],
    368 => ['nome' => 'L-sit no solo', 'grupo' => 'Core', 'arquivo' => '368.mp4'],
    370 => ['nome' => 'Mountain climber lento', 'grupo' => 'Core', 'arquivo' => '370.mp4'],
    381 => ['nome' => 'Prancha dinâmica (up-down)', 'grupo' => 'Core', 'arquivo' => '381.mp4'],
    392 => ['nome' => 'Toes to bar', 'grupo' => 'Core', 'arquivo' => '392.mp4'],
    397 => ['nome' => 'Bear crawl', 'grupo' => 'Funcional', 'arquivo' => '397.mp4'],
    348 => ['nome' => 'Abdominal declinado', 'grupo' => 'Core', 'arquivo' => '348.mp4'],
    365 => ['nome' => 'Hollow hold', 'grupo' => 'Core', 'arquivo' => '365.mp4'],
    369 => ['nome' => 'Limpador de para-brisa suspenso na barra', 'grupo' => 'Core', 'arquivo' => '369.mp4'],
    366 => ['nome' => 'Hollow rock', 'grupo' => 'Core', 'arquivo' => '366.mp4'],
    3 => ['nome' => 'Crossover', 'grupo' => 'Peito', 'arquivo' => '3.mp4'],
    31 => ['nome' => 'Pullover na polia alta', 'grupo' => 'Peito', 'arquivo' => '31.mp4'],
    82 => ['nome' => 'Remada baixa', 'grupo' => 'Costas', 'arquivo' => '82.mp4'],
    277 => ['nome' => 'Extensão de quadril na polia', 'grupo' => 'Posterior', 'arquivo' => '277.mp4'],
    324 => ['nome' => 'Glúteo no cabo (coice)', 'grupo' => 'Glúteos', 'arquivo' => '324.mp4'],
    371 => ['nome' => 'Pallof press', 'grupo' => 'Core', 'arquivo' => '371.mp4'],
    60 => ['nome' => 'Face pull', 'grupo' => 'Costas', 'arquivo' => '60.mp4'],
    75 => ['nome' => 'Puxada frontal pegada neutra', 'grupo' => 'Costas', 'arquivo' => '75.mp4'],
    76 => ['nome' => 'Puxada frontal pegada supinada', 'grupo' => 'Costas', 'arquivo' => '76.mp4'],
    80 => ['nome' => 'Puxador triângulo', 'grupo' => 'Costas', 'arquivo' => '80.mp4'],
    140 => ['nome' => 'Remada alta na polia baixa', 'grupo' => 'Ombros', 'arquivo' => '140.mp4'],
    142 => ['nome' => 'Rotação externa na polia', 'grupo' => 'Ombros', 'arquivo' => '142.mp4'],
    143 => ['nome' => 'Rotação interna na polia', 'grupo' => 'Ombros', 'arquivo' => '143.mp4'],
    301 => ['nome' => 'Abdução de quadril na polia', 'grupo' => 'Glúteos', 'arquivo' => '301.mp4'],
    303 => ['nome' => 'Adução de quadril na polia', 'grupo' => 'Glúteos', 'arquivo' => '303.mp4'],
    35 => ['nome' => 'Supino declinado', 'grupo' => 'Peito', 'arquivo' => '35.mp4'],
    39 => ['nome' => 'Supino inclinado', 'grupo' => 'Peito', 'arquivo' => '39.mp4'],
    155 => ['nome' => 'Rosca direta com barra W', 'grupo' => 'Bíceps', 'arquivo' => '155.mp4'],
    160 => ['nome' => 'Rosca inversa', 'grupo' => 'Bíceps', 'arquivo' => '160.mp4'],
    166 => ['nome' => 'Rosca Scott', 'grupo' => 'Bíceps', 'arquivo' => '166.mp4'],
    167 => ['nome' => 'Rosca Scott com barra W', 'grupo' => 'Bíceps', 'arquivo' => '167.mp4'],
    198 => ['nome' => 'Tríceps testa', 'grupo' => 'Tríceps', 'arquivo' => '198.mp4'],
    199 => ['nome' => 'Tríceps testa com barra W', 'grupo' => 'Tríceps', 'arquivo' => '199.mp4'],
    201 => ['nome' => 'Tríceps testa com halteres', 'grupo' => 'Tríceps', 'arquivo' => '201.mp4'],
    211 => ['nome' => 'Encolhimento com halteres', 'grupo' => 'Trapézio', 'arquivo' => '211.mp4'],
    57 => ['nome' => 'Bom dia com barra', 'grupo' => 'Costas', 'arquivo' => '57.mp4'],
    92 => ['nome' => 'Remada curvada pegada supinada', 'grupo' => 'Costas', 'arquivo' => '92.mp4'],
    359 => ['nome' => 'Dead bug', 'grupo' => 'Core', 'arquivo' => '359.mp4'],
];
