<?php

// Exercícios cortados da biblioteca (646 -> ~400), aplicados por
// `php artisan exercicios:podar-biblioteca`. Lista separada do comando pra
// dar pra revisar a curadoria sem ler código.
//
// Critérios do corte:
//  (a) variação quase idêntica de outra que fica (pegada/ângulo/aparelho trocado)
//  (b) é nota de prescrição, não exercício (isometria, pausa, parcial)
//  (c) equipamento que academia comum não tem (landmine, trap bar, trenó, escada)
//  (d) exótico demais — quase ninguém prescreve
//
// O comando NÃO apaga nada que esteja em uso num treino ou que tenha mídia
// própria de um personal, mesmo estando listado aqui.
return [
    'Caminhada do fazendeiro unilateral',
    'Enrolamento de corda',
    'Extensão de dedos com elástico',
    'Farmer walk com kettlebell',
    'Pinça com anilhas',
    'Preensão com hand grip',
    'Rosca de punho na máquina',
    'Rosca de punho na polia',
    'Rosca de punho por trás do corpo',
    'Rosca de punho sentado com barra W',
    'Rosca de punho unilateral',
    'Rosca inversa na polia baixa',
    'Rosca martelo para antebraço',
    'Rotação de punho com halter',
    'Suspensão com toalha',
    'Chin-up com foco em bíceps',
    'Rosca 45° no banco com elástico',
    'Rosca com barra reta na polia alta',
    'Rosca com pegada aberta',
    'Rosca com pegada fechada',
    'Rosca com toalha na barra',
    'Rosca de bíceps com kettlebell',
    'Rosca de bíceps unilateral com apoio no joelho',
    'Rosca deitado na polia baixa',
    'Rosca drag (arrasto)',
    'Rosca dupla na polia alta',
    'Rosca em pé no cabo cruzado',
    'Rosca invertida com barra W',
    'Rosca isométrica',
    'Rosca martelo cruzada',
    'Rosca no banco Scott com elástico',
    'Rosca parcial de pico',
    'Rosca punho neutro no banco inclinado',
    'Rosca simultânea supinada na polia',
    'Rosca spider com halteres',
    'Rosca unilateral na polia alta',
    'Rosca Zottman',
    'Abdominal borboleta',
    'Abdominal com pernas na bola',
    'Abdominal declinado com anilha',
    'Abdominal estrela',
    'Abdominal infra na paralela',
    'Abdominal na bola suíça',
    'Abdominal oblíquo no banco romano',
    'Dead bug com elástico',
    'Elevação de pernas com caneleira',
    'Elevação de pernas com rotação',
    'Elevação de pernas na paralela',
    'Farmer walk unilateral para core',
    'Isometria de core no TRX',
    'Mountain climber cruzado',
    'Pallof press com elástico',
    'Prancha com arrasto de peso',
    'Prancha com deslocamento lateral',
    'Prancha com peso nas costas',
    'Prancha na bola suíça',
    'Prancha no TRX',
    'Roda abdominal em pé',
    'Rotação russa com anilha',
    'Sit-up com medicine ball',
    'Woodchop invertido na polia',
    'Barra australiana (remada invertida)',
    'Encolhimento na barra fixa',
    'Hiperextensão lombar com anilha',
    'Levantamento terra deficitário',
    'Levantamento terra unilateral',
    'Pullover na polia para dorsal',
    'Puxada com corda',
    'Puxada com pegada fechada supinada',
    'Puxada dorsal na barra com toalha',
    'Puxada frontal com elástico',
    'Puxada por trás na máquina',
    'Rack pull',
    'Remada alta com halteres',
    'Remada cavalinho com barra livre',
    'Remada com barra W',
    'Remada com elástico sentado',
    'Remada com landmine',
    'Remada com pegada mista',
    'Remada em pé na polia baixa',
    'Remada Meadows',
    'Remada na polia alta sentado',
    'Remada renegada',
    'Remada sentado no solo com elástico',
    'Remada unilateral na polia ajoelhado',
    'Agachamento com kettlebell e rotação',
    'Agachamento isométrico com arremesso',
    'Arranco (snatch) com barra',
    'Arrasto de trenó',
    'Arremesso lateral de medicine ball',
    'Caminhada do garçom',
    'Caminhada do urso lateral',
    'Carregamento frontal (front rack carry)',
    'Corda naval em círculos',
    'Corrida em ziguezague',
    'Crab walk',
    'Deslocamento em escada de agilidade',
    'Empurrar trenó (prowler)',
    'Escada ergométrica',
    'Escalador na corda',
    'Flexão com burpee e salto na caixa',
    'Inchworm',
    'Kettlebell figure eight',
    'Levantamento olímpico clean',
    'Passe de peito com medicine ball',
    'Salto agachado lateral',
    'Salto lateral sobre cone',
    'Shadow boxing',
    'Snatch com kettlebell',
    'Sprint estacionário com elástico',
    'Abdução deitado com caneleira',
    'Abdução em pé na polia com tronco inclinado',
    'Abdução sentado na máquina com tronco inclinado',
    'Adução com bola entre os joelhos',
    'Agachamento cossaco com halter',
    'Caminhada de monstro com elástico',
    'Coice de glúteo no smith',
    'Elevação de quadril com pausa',
    'Elevação de quadril com uma perna e halter',
    'Elevação de quadril isométrica',
    'Elevação pélvica na bola suíça',
    'Extensão de quadril na máquina em pé',
    'Extensão de quadril no banco romano',
    'Fire hydrant com elástico',
    'Frog pump com halter',
    'Levantamento terra sumô para glúteo',
    'Passada reversa com elástico',
    'Step-up lateral com elástico',
    'Abdução com rotação (cubano)',
    'Crucifixo invertido com elástico',
    'Desenvolvimento com elástico',
    'Desenvolvimento com kettlebell',
    'Desenvolvimento com landmine',
    'Desenvolvimento sentado na máquina convergente',
    'Elevação em T no banco inclinado',
    'Elevação em W no banco inclinado',
    'Elevação frontal com corda',
    'Elevação lateral com pegada neutra 45°',
    'Elevação lateral inclinado',
    'Elevação lateral no banco inclinado',
    'Elevação lateral parcial (lateral raise 21)',
    'Elevação posterior unilateral na polia',
    'Encolhimento com barra por trás',
    'Encolhimento com trap bar',
    'Halo com kettlebell',
    'Press Bradford',
    'Remada alta com barra W',
    'Rotação externa deitado de lado',
    'Caminhada na ponta dos pés',
    'Panturrilha com elástico sentado',
    'Panturrilha com salto',
    'Panturrilha isométrica',
    'Panturrilha na barra guiada sentado',
    'Panturrilha no hack machine',
    'Pular corda para panturrilha',
    'Tibial anterior na parede',
    'Crucifixo com elástico',
    'Crucifixo com halteres no solo',
    'Flexão arqueiro',
    'Flexão com apoio instável',
    'Flexão com elevação de perna',
    'Flexão de braço com pés na bola',
    'Flexão explosiva com palma',
    'Flexão hindu',
    'Flexão isométrica',
    'Flexão pliométrica',
    'Flexão spiderman',
    'Press de peito com elástico',
    'Press de peito com landmine',
    'Press inclinado com kettlebell',
    'Supino com corrente',
    'Supino com halteres alternado',
    'Supino guilhotina',
    'Supino inclinado com barra W',
    'Supino Larsen',
    'Svend press',
    'Afundo no smith',
    'Afundo no step',
    'Agachamento afundo no smith',
    'Agachamento búlgaro no smith',
    'Agachamento com barra por cima da cabeça no smith',
    'Agachamento com correntes',
    'Agachamento com halteres em pegada frontal',
    'Agachamento com salto na caixa',
    'Agachamento hack com barra',
    'Agachamento isométrico com elástico',
    'Agachamento landmine',
    'Agachamento livre com pausa no fundo',
    'Agachamento na bola suíça',
    'Agachamento na máquina Smith pés à frente',
    'Agachamento overhead',
    'Agachamento pliométrico alternado',
    'Agachamento profundo com kettlebell',
    'Agachamento unilateral no banco',
    'Agachamento zercher',
    'Avanço búlgaro com kettlebell',
    'Avanço com rotação de tronco',
    'Extensora bilateral com pausa',
    'Extensora com pausa isométrica',
    'Hack machine invertido',
    'Leg press com elástico',
    'Leg press pausado',
    'Passada com kettlebell',
    'Sentar e levantar do banco',
    'Subida no step alta',
    'Wall sit com anilha',
    'Bom dia com kettlebell',
    'Elevação de quadril com barra e perna estendida',
    'Flexão de joelho no TRX',
    'Flexão nórdica assistida com elástico',
    'Flexora deitado com halter entre os pés',
    'Flexora na bola suíça bilateral',
    'Good morning com elástico',
    'Ponte de glúteo com elástico',
    'Puxada de calcanhar na bola',
    'Reverse hyper',
    'Stiff com barra W',
    'Stiff com pegada mista',
    'Swing unilateral com kettlebell',
    'Terra romeno com barra hexagonal',
    'Terra romeno deficitário',
    'Elevação de escápulas na barra fixa',
    'Encolhimento com elástico',
    'Encolhimento com trap bar pesado',
    'Encolhimento por trás no smith',
    'Prone Y raise no solo',
    'Shrug isométrico',
    'Extensão de tríceps no TRX',
    'Extensão de tríceps sentado na máquina convergente',
    'Extensão de tríceps unilateral na polia alta pegada supinada',
    'Flexão fechada com pés elevados',
    'JM press',
    'Mergulho no banco com peso',
    'Push-down parcial pesado',
    'Rosca francesa em pé com corda',
    'Tate press',
    'Tríceps banco (dips) elevado',
    'Tríceps com kettlebell acima da cabeça',
    'Tríceps francês com barra W deitado',
    'Tríceps kickback com elástico',
    'Tríceps na polia ajoelhado',
    'Tríceps na polia por trás da cabeça unilateral',
    'Tríceps no solo (skull crusher no chão)',
    'Tríceps pulley com barra reta pegada aberta',
];
