<?php

// Revisão do Hugo, 15/09/2026 (147 nomes). Faz parte da biblioteca_podada.php
// (os seeders não recriam nenhum destes), mas fica separada porque a remoção é
// julgamento do personal, não falta de demonstração: quase todos TÊM vídeo, e
// a trava "tem mídia, não apaga" do podar-biblioteca pouparia todos.
// `exercicios:podar-biblioteca --revisao-hugo` apaga estes ignorando essa trava
// (continua poupando o que está em treino ou tem mídia do personal).
return [
    // O personal assistiu aos 400 primeiros vídeos e reprovou estes: o vídeo não
    // representa o exercício, ou o exercício não vale a vaga na biblioteca.
    // Leitura item a item em database/revisao_hugo_2026-09-15.md.
    //
    // Diferente dos cortes anteriores, aqui a maioria TEM vídeo — a remoção é
    // por julgamento do personal, não por falta de demonstração. As entradas
    // correspondentes saíram de demonstracoes_geradas.php e dicas_demonstracao.php;
    // os .mp4 continuam no R2, então reverter é git revert, não regerar.

    // Peito
    'Crossover de baixo para cima',
    'Crossover na polia média',
    'Crossover unilateral',
    'Crucifixo na polia alta',
    'Crucifixo na polia baixa',
    'Crucifixo unilateral na polia',
    'Flexão de braço com abertura na toalha',
    'Flexão de braço com deslocamento lateral',
    'Flexão de braço declinada',
    'Flexão de braço diamante',
    'Flexão de braço nas argolas',
    'Floor press com halteres',
    'Peck deck (voador)',
    'Peck deck inclinado',
    'Pullover com halter',
    'Supino com pegada fechada',
    'Supino com pegada neutra',
    'Supino declinado na máquina',
    'Supino declinado no smith',
    'Supino inclinado com pegada neutra',
    'Supino inclinado unilateral com halter',
    'Supino máquina convergente',
    'Supino no chão (floor press)',
    'Voador na máquina unilateral',
    // Costas
    'Barra fixa com peso',
    'Barra fixa nas argolas',
    'Encolhimento na polia',
    'Face pull com elástico',
    'Face pull na polia alta',
    'Hiperextensão lombar',
    'Levantamento terra romeno com halteres',
    'Levantamento terra sumô',
    'Pull-up negativa',
    'Pulldown com braços estendidos',
    'Puxada frontal',
    'Puxada frontal com pegada em V',
    'Puxada frontal pegada aberta',
    'Puxada frontal unilateral',
    'Puxada na máquina sentado',
    'Puxada por trás',
    'Remada baixa pegada aberta',
    'Remada cavalinho',
    'Remada cavalinho com pegada neutra',
    'Remada curvada no smith',
    'Remada máquina pegada neutra',
    'Remada máquina unilateral',
    'Remada nas argolas com pés elevados',
    'Remada Pendlay',
    'Superman no solo',
    // Ombros
    'Crucifixo invertido',
    'Crucifixo invertido na máquina',
    'Crucifixo invertido na polia',
    'Desenvolvimento com pegada neutra',
    'Desenvolvimento em parada de mão na parede',
    'Desenvolvimento militar',
    'Desenvolvimento por trás da nuca',
    'Desenvolvimento sentado com barra',
    'Desenvolvimento sentado com halteres',
    'Desenvolvimento unilateral com halter',
    'Elevação em Y no banco inclinado',
    'Elevação frontal com barra',
    'Elevação frontal na polia',
    'Elevação lateral com halteres em pé',
    'Elevação lateral na máquina',
    'Elevação lateral na polia',
    'Flexão de braço em pique (pike push-up)',
    'Parada de mão na parede',
    // Bíceps
    'Rosca alternada com rotação',
    'Rosca bayesiana com o braço atrás do corpo',
    'Rosca concentrada na polia',
    'Rosca de bíceps na máquina',
    'Rosca direta',
    'Rosca direta com halteres',
    'Rosca martelo na corda',
    'Rosca nas argolas',
    // Tríceps
    'Extensão de tríceps com elástico',
    'Extensão de tríceps deitado com halteres neutro',
    'Extensão de tríceps nas argolas',
    'Tríceps corda acima da cabeça',
    'Tríceps na máquina unilateral',
    'Tríceps na polia unilateral',
    'Tríceps testa com elástico',
    'Tríceps testa na polia baixa',
    // Antebraço
    'Rosca de punho',
    'Rosca de punho com halteres',
    'Rosca de punho invertida',
    'Rosca de punho invertida com halteres',
    'Rosca inversa em pé',
    // Trapézio
    'Elevação em Y na polia',
    'Encolhimento inclinado no banco',
    'Encolhimento na máquina',
    'Encolhimento unilateral com halter',
    'Puxada alta no cavalete',
    'Remada alta explosiva',
    // Pernas
    'Afundo lateral',
    'Afundo reverso',
    'Agachamento box squat',
    'Agachamento com barra baixa',
    'Agachamento pausado',
    'Avanço em diagonal',
    'Belt squat na máquina',
    'Leg press 45°',
    'Leg press horizontal',
    'Leg press pés afastados',
    'Leg press pés altos',
    'Leg press pés baixos',
    'Leg press pés juntos',
    'Leg press unilateral',
    'Leg press vertical',
    'Passada com halteres',
    // Posterior
    'Bom dia sentado',
    'Cadeira flexora unilateral',
    'Flexão de joelho com caneleira',
    'Flexão nórdica',
    'Glute ham raise',
    'Mesa flexora com pausa',
    'Mesa flexora unilateral',
    'Ponte de glúteo com uma perna',
    'Stiff unilateral',
    // Glúteos
    'Cadeira abdutora',
    'Chute de glúteo na polia (kickback)',
    'Coice de glúteo com elástico',
    'Coice de glúteo na máquina',
    'Elevação de quadril com halter',
    'Elevação de quadril com pés no banco',
    'Extensão de quadril em quatro apoios',
    'Fire hydrant',
    'Frog pump',
    'Glúteo quatro apoios',
    'Ponte de glúteo com barra',
    'Ponte de glúteo com elevação alternada',
    // Panturrilha
    'Panturrilha burro (donkey calf)',
    'Panturrilha com pés para dentro',
    'Panturrilha com pés para fora',
    'Panturrilha em pé',
    'Panturrilha em pé na máquina',
    'Panturrilha sentado',
    'Panturrilha sentado com anilha',
    'Panturrilha sentado unilateral',
    'Panturrilha unilateral com halter',
    'Tibial anterior com elástico',
    // Core
    'Abdominal na polia alta (ajoelhado)',
    'Abdominal supra com pés apoiados',
    'Prancha com apoio dos antebraços',
    'Roda abdominal (ab wheel)',
    'Rotação de tronco na polia (woodchop)',
    'Serra abdominal na toalha',
];
