<?php

// Medidas caseiras dos alimentos, com o peso em gramas de cada uma.
//
// Fonte: IBGE, Pesquisa de Orçamentos Familiares 2008-2009 — "Tabela de
// Medidas Referidas para os Alimentos Consumidos no Brasil".
// https://ftp.ibge.gov.br/Orcamentos_Familiares/Pesquisa_de_Orcamentos_Familiares_2008_2009/Tabela_de_Medidas_Referidas_para_os_Alimentos_Consumidos_no_Brasil/
//
// Existe porque "1 concha de feijão" é o que a pessoa entende; "140 g" não.
//
// A chave é o código da TACO, então o vínculo é com database/alimentos_taco.php.
// Casar as duas tabelas NÃO é trivial: elas usam taxonomias diferentes, e o
// pareamento automático ingênuo produz erro grosseiro (a gema herdando o peso
// do ovo inteiro, o molho de tomate herdando o do tomate). Por isso:
//
//   'curado'     -> par TACO<->IBGE conferido à mão, um por um. São os
//                   alimentos que dominam um diário brasileiro, e justamente
//                   os que o pareamento automático errava.
//   'automatico' -> casamento estrito: todo qualificador do nome na TACO
//                   precisa existir também no nome do IBGE. Cobre menos
//                   alimentos de propósito — preferimos alimento SEM medida
//                   (cai no campo de gramas, que já existe) a alimento com
//                   medida de outra coisa.
//
// Ver database/README-taco.md para como conferir uma reimportação.
return [
    1 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Caneca', 'gramas' => 100.0], ['nome' => 'Colher de servir', 'gramas' => 63.0], ['nome' => 'Colher de chá', 'gramas' => 5.0], ['nome' => 'Colher de sobremesa', 'gramas' => 10.0], ['nome' => 'Colher de sopa', 'gramas' => 20.0], ['nome' => 'Concha', 'gramas' => 117.0], ['nome' => 'Escumadeira', 'gramas' => 59.0], ['nome' => 'Prato raso', 'gramas' => 100.0]]], // Arroz, integral, cozido
    3 => ['origem' => 'curado', 'medidas' => [['nome' => 'Caneca', 'gramas' => 100.0], ['nome' => 'Colher de servir', 'gramas' => 45.0], ['nome' => 'Colher de chá', 'gramas' => 6.3], ['nome' => 'Colher de sobremesa', 'gramas' => 12.5], ['nome' => 'Colher de sopa', 'gramas' => 25.0], ['nome' => 'Concha', 'gramas' => 100.0], ['nome' => 'Copo americano', 'gramas' => 100.0], ['nome' => 'Copo grande', 'gramas' => 200.0], ['nome' => 'Copo médio', 'gramas' => 200.0], ['nome' => 'Escumadeira', 'gramas' => 85.0], ['nome' => 'Pote', 'gramas' => 100.0], ['nome' => 'Prato raso', 'gramas' => 100.0]]], // Arroz, tipo 1, cozido
    5 => ['origem' => 'curado', 'medidas' => [['nome' => 'Caneca', 'gramas' => 100.0], ['nome' => 'Colher de servir', 'gramas' => 45.0], ['nome' => 'Colher de chá', 'gramas' => 6.3], ['nome' => 'Colher de sobremesa', 'gramas' => 12.5], ['nome' => 'Colher de sopa', 'gramas' => 25.0], ['nome' => 'Concha', 'gramas' => 100.0], ['nome' => 'Copo americano', 'gramas' => 100.0], ['nome' => 'Copo grande', 'gramas' => 200.0], ['nome' => 'Copo médio', 'gramas' => 200.0], ['nome' => 'Escumadeira', 'gramas' => 85.0], ['nome' => 'Pote', 'gramas' => 100.0], ['nome' => 'Prato raso', 'gramas' => 100.0]]], // Arroz, tipo 2, cozido
    15 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Fatia', 'gramas' => 80.0], ['nome' => 'Pedaço', 'gramas' => 80.0]]], // Bolo, pronto, aipim
    16 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Fatia', 'gramas' => 60.0], ['nome' => 'Pedaço', 'gramas' => 60.0]]], // Bolo, pronto, chocolate
    17 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Fatia', 'gramas' => 60.0], ['nome' => 'Pedaço', 'gramas' => 60.0]]], // Bolo, pronto, coco
    18 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Fatia', 'gramas' => 60.0], ['nome' => 'Pedaço', 'gramas' => 60.0]]], // Bolo, pronto, milho
    39 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 50.0], ['nome' => 'Colher de sopa', 'gramas' => 25.0], ['nome' => 'Concha', 'gramas' => 110.0], ['nome' => 'Escumadeira', 'gramas' => 110.0], ['nome' => 'Pacote', 'gramas' => 320.0], ['nome' => 'Pote', 'gramas' => 320.0], ['nome' => 'Prato raso', 'gramas' => 320.0], ['nome' => 'Unidade', 'gramas' => 320.0]]], // Macarrão, instantâneo
    53 => ['origem' => 'curado', 'medidas' => [['nome' => 'Fatia', 'gramas' => 25.0], ['nome' => 'Metade', 'gramas' => 25.0], ['nome' => 'Pedaço', 'gramas' => 25.0], ['nome' => 'Rodela', 'gramas' => 16.7], ['nome' => 'Unidade', 'gramas' => 50.0]]], // Pão, trigo, francês
    75 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 50.0], ['nome' => 'Colher de sopa', 'gramas' => 7.0], ['nome' => 'Folha', 'gramas' => 5.0], ['nome' => 'Prato raso', 'gramas' => 80.0]]], // Agrião, cru
    77 => ['origem' => 'curado', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 16.0], ['nome' => 'Colher de chá', 'gramas' => 2.0], ['nome' => 'Colher de sobremesa', 'gramas' => 4.0], ['nome' => 'Colher de sopa', 'gramas' => 8.0], ['nome' => 'Concha', 'gramas' => 32.0], ['nome' => 'Escumadeira', 'gramas' => 16.0], ['nome' => 'Folha', 'gramas' => 10.0], ['nome' => 'Metade', 'gramas' => 100.0], ['nome' => 'Prato raso', 'gramas' => 50.0], ['nome' => 'Unidade', 'gramas' => 200.0], ['nome' => 'Unidade pequena', 'gramas' => 130.0]]], // Alface, americana, crua
    78 => ['origem' => 'curado', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 16.0], ['nome' => 'Colher de chá', 'gramas' => 2.0], ['nome' => 'Colher de sobremesa', 'gramas' => 4.0], ['nome' => 'Colher de sopa', 'gramas' => 8.0], ['nome' => 'Concha', 'gramas' => 32.0], ['nome' => 'Escumadeira', 'gramas' => 16.0], ['nome' => 'Folha', 'gramas' => 10.0], ['nome' => 'Metade', 'gramas' => 100.0], ['nome' => 'Prato raso', 'gramas' => 50.0], ['nome' => 'Unidade', 'gramas' => 200.0], ['nome' => 'Unidade pequena', 'gramas' => 130.0]]], // Alface, crespa, crua
    79 => ['origem' => 'curado', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 16.0], ['nome' => 'Colher de chá', 'gramas' => 2.0], ['nome' => 'Colher de sobremesa', 'gramas' => 4.0], ['nome' => 'Colher de sopa', 'gramas' => 8.0], ['nome' => 'Concha', 'gramas' => 32.0], ['nome' => 'Escumadeira', 'gramas' => 16.0], ['nome' => 'Folha', 'gramas' => 10.0], ['nome' => 'Metade', 'gramas' => 100.0], ['nome' => 'Prato raso', 'gramas' => 50.0], ['nome' => 'Unidade', 'gramas' => 200.0], ['nome' => 'Unidade pequena', 'gramas' => 130.0]]], // Alface, lisa, crua
    84 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 50.0], ['nome' => 'Colher de sopa', 'gramas' => 25.0], ['nome' => 'Folha', 'gramas' => 12.0], ['nome' => 'Prato raso', 'gramas' => 24.0]]], // Almeirão, cru
    85 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 50.0], ['nome' => 'Colher de sopa', 'gramas' => 25.0]]], // Almeirão, refogado
    88 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Pedaço', 'gramas' => 70.0]]], // Batata, doce, cozida
    91 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de sopa', 'gramas' => 30.0], ['nome' => 'Unidade', 'gramas' => 140.0]]], // Batata, inglesa, cozida
    93 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de sopa', 'gramas' => 30.0], ['nome' => 'Unidade', 'gramas' => 140.0]]], // Batata, inglesa, frita
    95 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Unidade', 'gramas' => 200.0]]], // Berinjela, cozida
    97 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Pedaço', 'gramas' => 12.0], ['nome' => 'Rodela', 'gramas' => 12.0]]], // Beterraba, cozida
    100 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 20.0]]], // Brócolis, cozido
    101 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 20.0], ['nome' => 'Colher de sobremesa', 'gramas' => 5.0]]], // Brócolis, cru
    109 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de sopa', 'gramas' => 12.0], ['nome' => 'Copo americano', 'gramas' => 48.0], ['nome' => 'Copo grande', 'gramas' => 96.0], ['nome' => 'Copo médio', 'gramas' => 96.0], ['nome' => 'Unidade', 'gramas' => 120.0]]], // Cenoura, cozida
    113 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 45.0], ['nome' => 'Colher de sopa', 'gramas' => 20.0], ['nome' => 'Escumadeira', 'gramas' => 110.0], ['nome' => 'Fatia', 'gramas' => 30.0], ['nome' => 'Pedaço', 'gramas' => 30.0], ['nome' => 'Unidade', 'gramas' => 230.0]]], // Chuchu, cru
    118 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de sopa', 'gramas' => 25.0]]], // Couve-flor, cozida
    126 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Escumadeira', 'gramas' => 110.0], ['nome' => 'Rodela', 'gramas' => 30.0], ['nome' => 'Unidade', 'gramas' => 125.0]]], // Inhame, cru
    127 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 95.0], ['nome' => 'Colher de sopa', 'gramas' => 60.0], ['nome' => 'Unidade', 'gramas' => 26.0]]], // Jiló, cru
    129 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 60.0], ['nome' => 'Pedaço', 'gramas' => 100.0]]], // Mandioca, cozida
    132 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 60.0], ['nome' => 'Pedaço', 'gramas' => 100.0]]], // Mandioca, frita
    134 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de sopa', 'gramas' => 40.0]]], // Maxixe, cru
    140 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Unidade', 'gramas' => 20.0], ['nome' => 'Unidade pequena', 'gramas' => 10.0]]], // Pão, de queijo, assado
    147 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de sopa', 'gramas' => 40.0], ['nome' => 'Unidade', 'gramas' => 18.0]]], // Quiabo, cru
    148 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 22.0], ['nome' => 'Colher de sopa', 'gramas' => 11.0], ['nome' => 'Escumadeira', 'gramas' => 22.0], ['nome' => 'Fatia', 'gramas' => 4.0], ['nome' => 'Rodela', 'gramas' => 12.5], ['nome' => 'Unidade', 'gramas' => 25.0]]], // Rabanete, cru
    157 => ['origem' => 'curado', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 60.0], ['nome' => 'Colher de chá', 'gramas' => 7.5], ['nome' => 'Colher de sobremesa', 'gramas' => 15.0], ['nome' => 'Concha', 'gramas' => 120.0], ['nome' => 'Escumadeira', 'gramas' => 60.0], ['nome' => 'Fatia', 'gramas' => 15.0], ['nome' => 'Metade', 'gramas' => 50.0], ['nome' => 'Pedaço', 'gramas' => 15.0], ['nome' => 'Prato raso', 'gramas' => 60.0], ['nome' => 'Rodela', 'gramas' => 15.0], ['nome' => 'Unidade', 'gramas' => 100.0], ['nome' => 'Unidade pequena', 'gramas' => 50.0]]], // Tomate, com semente, cru
    159 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 45.0], ['nome' => 'Colher de chá', 'gramas' => 8.5], ['nome' => 'Colher de sobremesa', 'gramas' => 17.0], ['nome' => 'Colher de sopa', 'gramas' => 20.0], ['nome' => 'Concha', 'gramas' => 80.0], ['nome' => 'Escumadeira', 'gramas' => 45.0], ['nome' => 'Prato raso', 'gramas' => 40.0]]], // Tomate, molho industrializado
    179 => ['origem' => 'curado', 'medidas' => [['nome' => 'Fatia', 'gramas' => 26.0], ['nome' => 'Metade', 'gramas' => 37.5], ['nome' => 'Pedaço', 'gramas' => 16.0], ['nome' => 'Prato raso', 'gramas' => 235.0], ['nome' => 'Unidade', 'gramas' => 75.0], ['nome' => 'Unidade pequena', 'gramas' => 56.3]]], // Banana, nanica, crua
    182 => ['origem' => 'curado', 'medidas' => [['nome' => 'Fatia', 'gramas' => 26.0], ['nome' => 'Metade', 'gramas' => 37.5], ['nome' => 'Pedaço', 'gramas' => 16.0], ['nome' => 'Prato raso', 'gramas' => 235.0], ['nome' => 'Unidade', 'gramas' => 75.0], ['nome' => 'Unidade pequena', 'gramas' => 56.3]]], // Banana, prata, crua
    214 => ['origem' => 'curado', 'medidas' => [['nome' => 'Copo americano', 'gramas' => 150.0], ['nome' => 'Copo grande', 'gramas' => 300.0], ['nome' => 'Copo médio', 'gramas' => 240.0], ['nome' => 'Fatia', 'gramas' => 18.0], ['nome' => 'Metade', 'gramas' => 90.0], ['nome' => 'Pedaço', 'gramas' => 18.0], ['nome' => 'Rodela', 'gramas' => 18.0], ['nome' => 'Unidade', 'gramas' => 180.0], ['nome' => 'Unidade pequena', 'gramas' => 90.0]]], // Laranja, pêra, crua
    215 => ['origem' => 'curado', 'medidas' => [['nome' => 'Caneca', 'gramas' => 300.0], ['nome' => 'Copo americano', 'gramas' => 150.0], ['nome' => 'Copo grande', 'gramas' => 300.0], ['nome' => 'Copo médio', 'gramas' => 240.0], ['nome' => 'Xícara de café', 'gramas' => 50.0]]], // Laranja, pêra, suco
    222 => ['origem' => 'curado', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 50.0], ['nome' => 'Colher de sopa', 'gramas' => 25.0], ['nome' => 'Escumadeira', 'gramas' => 110.0], ['nome' => 'Fatia', 'gramas' => 37.5], ['nome' => 'Metade', 'gramas' => 75.0], ['nome' => 'Pacote', 'gramas' => 320.0], ['nome' => 'Pedaço', 'gramas' => 37.5], ['nome' => 'Pote', 'gramas' => 320.0], ['nome' => 'Prato raso', 'gramas' => 320.0], ['nome' => 'Unidade pequena', 'gramas' => 90.0]]], // Maçã, Fuji, com casca, crua
    225 => ['origem' => 'curado', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 70.0], ['nome' => 'Colher de sopa', 'gramas' => 40.0], ['nome' => 'Concha', 'gramas' => 140.0], ['nome' => 'Fatia', 'gramas' => 170.0], ['nome' => 'Metade', 'gramas' => 155.0], ['nome' => 'Pedaço', 'gramas' => 120.0], ['nome' => 'Rodela', 'gramas' => 170.0], ['nome' => 'Unidade', 'gramas' => 310.0], ['nome' => 'Unidade pequena', 'gramas' => 270.0]]], // Mamão, Formosa, cru
    272 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de chá', 'gramas' => 2.0], ['nome' => 'Colher de sopa', 'gramas' => 8.0], ['nome' => 'Concha', 'gramas' => 32.0]]], // Óleo, de soja
    323 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Fatia', 'gramas' => 15.0]]], // Apresuntado
    403 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Pedaço', 'gramas' => 55.0]]], // Frango, inteiro, sem pele, assado
    406 => ['origem' => 'curado', 'medidas' => [['nome' => 'Bife', 'gramas' => 100.0], ['nome' => 'Colher de sopa', 'gramas' => 20.0], ['nome' => 'Concha', 'gramas' => 80.0], ['nome' => 'Filé', 'gramas' => 100.0], ['nome' => 'Pedaço', 'gramas' => 55.0]]], // Frango, peito, com pele, assado
    408 => ['origem' => 'curado', 'medidas' => [['nome' => 'Bife', 'gramas' => 100.0], ['nome' => 'Colher de servir', 'gramas' => 40.0], ['nome' => 'Colher de sopa', 'gramas' => 20.0], ['nome' => 'Concha', 'gramas' => 80.0], ['nome' => 'Escumadeira', 'gramas' => 40.0], ['nome' => 'Pedaço', 'gramas' => 55.0]]], // Frango, peito, sem pele, cozido
    410 => ['origem' => 'curado', 'medidas' => [['nome' => 'Bife', 'gramas' => 100.0], ['nome' => 'Colher de sopa', 'gramas' => 20.0], ['nome' => 'Filé', 'gramas' => 100.0], ['nome' => 'Pedaço', 'gramas' => 55.0]]], // Frango, peito, sem pele, grelhado
    424 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Fatia', 'gramas' => 15.0], ['nome' => 'Pedaço', 'gramas' => 15.0]]], // Mortadela
    440 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Pedaço', 'gramas' => 12.0], ['nome' => 'Unidade', 'gramas' => 50.0], ['nome' => 'Unidade pequena', 'gramas' => 12.0]]], // Quibe, assado
    442 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Pedaço', 'gramas' => 12.0], ['nome' => 'Unidade', 'gramas' => 50.0], ['nome' => 'Unidade pequena', 'gramas' => 12.0]]], // Quibe, frito
    443 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Fatia', 'gramas' => 20.0]]], // Salame
    445 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Pedaço', 'gramas' => 10.0]]], // Toucinho, frito
    447 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 30.0], ['nome' => 'Colher de chá', 'gramas' => 5.0], ['nome' => 'Colher de sobremesa', 'gramas' => 20.0], ['nome' => 'Colher de sopa', 'gramas' => 15.0], ['nome' => 'Copo americano', 'gramas' => 150.0], ['nome' => 'Copo médio', 'gramas' => 240.0], ['nome' => 'Pote', 'gramas' => 150.0]]], // Creme de Leite
    448 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de sopa', 'gramas' => 15.0], ['nome' => 'Copo americano', 'gramas' => 150.0], ['nome' => 'Copo grande', 'gramas' => 300.0], ['nome' => 'Copo médio', 'gramas' => 240.0], ['nome' => 'Pote', 'gramas' => 200.0]]], // Iogurte, natural
    449 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Copo americano', 'gramas' => 150.0], ['nome' => 'Copo médio', 'gramas' => 240.0], ['nome' => 'Pote', 'gramas' => 200.0]]], // Iogurte, natural, desnatado
    453 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 30.0], ['nome' => 'Colher de chá', 'gramas' => 2.0], ['nome' => 'Colher de sobremesa', 'gramas' => 10.0], ['nome' => 'Colher de sopa', 'gramas' => 15.0], ['nome' => 'Copo grande', 'gramas' => 300.0], ['nome' => 'Copo médio', 'gramas' => 240.0], ['nome' => 'Lata', 'gramas' => 395.0], ['nome' => 'Pote', 'gramas' => 150.0], ['nome' => 'Xícara de café', 'gramas' => 50.0]]], // Leite, condensado
    454 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Copo americano', 'gramas' => 150.0], ['nome' => 'Copo médio', 'gramas' => 240.0], ['nome' => 'Xícara de café', 'gramas' => 50.0]]], // Leite, de cabra
    458 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Caneca', 'gramas' => 300.0], ['nome' => 'Copo americano', 'gramas' => 150.0], ['nome' => 'Copo grande', 'gramas' => 300.0], ['nome' => 'Copo médio', 'gramas' => 240.0], ['nome' => 'Prato raso', 'gramas' => 240.0], ['nome' => 'Xícara de café', 'gramas' => 50.0]]], // Leite, de vaca, integral
    460 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Copo grande', 'gramas' => 300.0], ['nome' => 'Copo médio', 'gramas' => 240.0], ['nome' => 'Pote', 'gramas' => 80.0], ['nome' => 'Unidade', 'gramas' => 80.0]]], // Leite, fermentado
    467 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Fatia', 'gramas' => 15.0]]], // Queijo, prato
    469 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de sopa', 'gramas' => 44.0], ['nome' => 'Fatia', 'gramas' => 35.0]]], // Queijo, ricota
    471 => ['origem' => 'curado', 'medidas' => [['nome' => 'Caneca', 'gramas' => 300.0], ['nome' => 'Copo americano', 'gramas' => 150.0], ['nome' => 'Copo grande', 'gramas' => 300.0], ['nome' => 'Copo médio', 'gramas' => 240.0], ['nome' => 'Xícara de café', 'gramas' => 50.0]]], // Café, infusão 10%
    473 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Caneca', 'gramas' => 300.0], ['nome' => 'Concha', 'gramas' => 50.0], ['nome' => 'Copo americano', 'gramas' => 150.0], ['nome' => 'Copo grande', 'gramas' => 300.0], ['nome' => 'Copo médio', 'gramas' => 240.0]]], // Cana, caldo de
    478 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Copo americano', 'gramas' => 150.0], ['nome' => 'Copo grande', 'gramas' => 300.0], ['nome' => 'Copo médio', 'gramas' => 240.0], ['nome' => 'Unidade', 'gramas' => 340.0]]], // Coco, água de
    488 => ['origem' => 'curado', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 45.0], ['nome' => 'Colher de chá', 'gramas' => 3.8], ['nome' => 'Colher de sopa', 'gramas' => 15.0], ['nome' => 'Pedaço', 'gramas' => 22.5], ['nome' => 'Rodela', 'gramas' => 10.0], ['nome' => 'Unidade', 'gramas' => 45.0]]], // Ovo, de galinha, inteiro, cozido/10minutos
    490 => ['origem' => 'curado', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 45.0], ['nome' => 'Colher de sopa', 'gramas' => 15.0], ['nome' => 'Escumadeira', 'gramas' => 45.0], ['nome' => 'Fatia', 'gramas' => 10.0], ['nome' => 'Metade', 'gramas' => 25.0], ['nome' => 'Pedaço', 'gramas' => 25.0], ['nome' => 'Unidade', 'gramas' => 50.0]]], // Ovo, de galinha, inteiro, frito
    493 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de sopa', 'gramas' => 19.0]]], // Açúcar, mascavo
    502 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Copo americano', 'gramas' => 200.0], ['nome' => 'Pedaço', 'gramas' => 34.0], ['nome' => 'Unidade', 'gramas' => 200.0]]], // Geléia, mocotó, natural
    504 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Pedaço', 'gramas' => 90.0]]], // Maria mole
    506 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Fatia', 'gramas' => 60.0], ['nome' => 'Pedaço', 'gramas' => 60.0]]], // Marmelada
    508 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de chá', 'gramas' => 3.0], ['nome' => 'Colher de sobremesa', 'gramas' => 9.0], ['nome' => 'Colher de sopa', 'gramas' => 15.0], ['nome' => 'Copo americano', 'gramas' => 150.0]]], // Melado
    509 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Unidade', 'gramas' => 35.0], ['nome' => 'Unidade pequena', 'gramas' => 20.0]]], // Quindim
    510 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Pedaço', 'gramas' => 55.0]]], // Rapadura
    523 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de chá', 'gramas' => 5.0], ['nome' => 'Colher de sopa', 'gramas' => 20.0], ['nome' => 'Concha', 'gramas' => 80.0], ['nome' => 'Copo americano', 'gramas' => 150.0], ['nome' => 'Copo grande', 'gramas' => 300.0], ['nome' => 'Xícara de café', 'gramas' => 50.0]]], // Leite, de coco
    525 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Unidade', 'gramas' => 100.0]]], // Acarajé
    526 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 60.0], ['nome' => 'Colher de sopa', 'gramas' => 30.0], ['nome' => 'Concha', 'gramas' => 120.0], ['nome' => 'Escumadeira', 'gramas' => 60.0], ['nome' => 'Prato raso', 'gramas' => 100.0]]], // Arroz carreteiro
    534 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 60.0], ['nome' => 'Colher de sopa', 'gramas' => 35.0], ['nome' => 'Fatia', 'gramas' => 150.0], ['nome' => 'Prato raso', 'gramas' => 300.0]]], // Cuscuz, paulista
    543 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 70.0], ['nome' => 'Concha', 'gramas' => 225.0]]], // Maniçoba
    544 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 100.0], ['nome' => 'Colher de sobremesa', 'gramas' => 24.0], ['nome' => 'Colher de sopa', 'gramas' => 35.0], ['nome' => 'Concha', 'gramas' => 100.0], ['nome' => 'Escumadeira', 'gramas' => 100.0]]], // Quibebe
    553 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 40.0], ['nome' => 'Concha', 'gramas' => 130.0]]], // Vaca atolada
    554 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 77.0], ['nome' => 'Colher de sopa', 'gramas' => 25.0], ['nome' => 'Concha', 'gramas' => 150.0], ['nome' => 'Copo médio', 'gramas' => 150.0], ['nome' => 'Prato raso', 'gramas' => 150.0]]], // Vatapá
    561 => ['origem' => 'curado', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 35.0], ['nome' => 'Colher de chá', 'gramas' => 4.3], ['nome' => 'Colher de sobremesa', 'gramas' => 8.5], ['nome' => 'Colher de sopa', 'gramas' => 17.0], ['nome' => 'Concha', 'gramas' => 140.0], ['nome' => 'Copo americano', 'gramas' => 140.0], ['nome' => 'Copo médio', 'gramas' => 280.0], ['nome' => 'Escumadeira', 'gramas' => 35.0], ['nome' => 'Prato raso', 'gramas' => 140.0]]], // Feijão, carioca, cozido
    567 => ['origem' => 'curado', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 35.0], ['nome' => 'Colher de chá', 'gramas' => 4.3], ['nome' => 'Colher de sobremesa', 'gramas' => 8.5], ['nome' => 'Colher de sopa', 'gramas' => 17.0], ['nome' => 'Concha', 'gramas' => 140.0], ['nome' => 'Copo americano', 'gramas' => 140.0], ['nome' => 'Copo médio', 'gramas' => 280.0], ['nome' => 'Escumadeira', 'gramas' => 35.0], ['nome' => 'Prato raso', 'gramas' => 140.0]]], // Feijão, preto, cozido
    577 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de servir', 'gramas' => 32.0], ['nome' => 'Colher de sopa', 'gramas' => 18.0], ['nome' => 'Concha', 'gramas' => 160.0], ['nome' => 'Escumadeira', 'gramas' => 32.0], ['nome' => 'Prato raso', 'gramas' => 160.0]]], // Lentilha, cozida
    594 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Colher de chá', 'gramas' => 1.5], ['nome' => 'Colher de sobremesa', 'gramas' => 3.0], ['nome' => 'Colher de sopa', 'gramas' => 13.0], ['nome' => 'Prato raso', 'gramas' => 26.0]]], // Linhaça, semente
    595 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Unidade', 'gramas' => 4.0]]], // Pinhão, cozido
    596 => ['origem' => 'automatico', 'medidas' => [['nome' => 'Unidade', 'gramas' => 22.5], ['nome' => 'Unidade pequena', 'gramas' => 16.9]]], // Pupunha, cozida
];
