<?php

namespace Database\Seeders;

use App\Models\Exercise;
use Illuminate\Database\Seeder;

/** Biblioteca de exercícios — espelha backend/src/db/seed.ts do Node (fonte: wger.de, CC-BY-SA). */
class ExerciseSeeder extends Seeder
{
    public function run(): void
    {
        foreach (self::exercicios() as $ex) {
            Exercise::updateOrCreate(['name' => $ex['name']], $ex);
        }
    }

    private static function exercicios(): array
    {
        return [
            [
                'name' => 'Rosca direta com barra reta',
                'muscle_group' => 'Bíceps',
                'equipment' => 'Barra',
                'instructions' => '7 reps na metade inferior, 7 na superior e 7 no movimento completo.',
                'image_url' => '/exercise-photos/rosca-21.png',
                'image_credit' => 'Franpol · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Rosca alternada',
                'muscle_group' => 'Bíceps',
                'equipment' => 'Halteres',
                'instructions' => 'Flexione um braço de cada vez, girando o punho ao final do movimento.',
                'image_url' => '/exercise-photos/rosca-alternada.png',
                'image_credit' => 'Franpol · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Rosca concentrada',
                'muscle_group' => 'Bíceps',
                'equipment' => 'Halter',
                'instructions' => 'Cotovelo apoiado na coxa, flexione focando na contração do bíceps.',
                'image_url' => '/exercise-photos/rosca-concentrada.png',
                'image_credit' => 'Franpol · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Rosca inversa',
                'muscle_group' => 'Bíceps',
                'equipment' => 'Barra',
                'instructions' => 'Pegada pronada (palmas para baixo), flexione trabalhando antebraço e bíceps.',
                'image_url' => '/exercise-photos/rosca-inversa.png',
                'image_credit' => 'Franpol · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Rosca martelo com halteres',
                'muscle_group' => 'Bíceps',
                'equipment' => 'Halteres',
                'instructions' => 'Pegada neutra (palmas viradas para dentro), flexione mantendo os cotovelos fixos.',
                'image_url' => '/exercise-photos/rosca-martelo.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Rosca Scott com barra reta',
                'muscle_group' => 'Bíceps',
                'equipment' => 'Barra W',
                'instructions' => 'Braços apoiados no banco Scott, flexione sem tirar o cotovelo do apoio.',
                'image_url' => '/exercise-photos/rosca-scott.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Abdominal infra (elevação de pernas)',
                'muscle_group' => 'Core',
                'equipment' => 'Peso corporal',
                'instructions' => 'Deitado, eleve as pernas estendidas até 90° controlando a descida.',
                'image_url' => '/exercise-photos/abdominal-infra-elevacao-de-pernas.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Abdominal oblíquo unilateral',
                'muscle_group' => 'Core',
                'equipment' => 'Peso corporal',
                'instructions' => 'Eleve o tronco girando em direção ao joelho oposto.',
                'image_url' => '/exercise-photos/abdominal-obliquo.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Abdominal supra (crunch)',
                'muscle_group' => 'Core',
                'equipment' => 'Peso corporal',
                'instructions' => 'Eleve o tronco em direção aos joelhos contraindo o abdômen.',
                'image_url' => '/exercise-photos/abdominal-supra-crunch.png',
                'image_credit' => 'wger.de · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Prancha abdominal',
                'muscle_group' => 'Core',
                'equipment' => 'Peso corporal',
                'instructions' => 'Mantenha o corpo alinhado da cabeça aos calcanhares, contraindo o abdômen.',
                'image_url' => '/exercise-photos/prancha-abdominal.png',
                'image_credit' => 'utkb · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Rotação russa (russian twist)',
                'muscle_group' => 'Core',
                'equipment' => 'Peso corporal',
                'instructions' => 'Tronco levemente inclinado para trás, gire de um lado para o outro.',
                'image_url' => '/exercise-photos/rotacao-russa-russian-twist.png',
                'image_credit' => 'lion · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Barra fixa (pull-up)',
                'muscle_group' => 'Costas',
                'equipment' => 'Peso corporal',
                'instructions' => 'Puxe o corpo até o queixo passar a barra, controle a descida.',
                'image_url' => '/exercise-photos/barra-fixa-pull-up.jpg',
                'image_credit' => 'Imobard · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Face pull',
                'muscle_group' => 'Costas',
                'equipment' => 'Polia',
                'instructions' => 'Puxe a corda em direção ao rosto, cotovelos altos e abertos.',
                'image_url' => '/exercise-photos/face-pull.jpg',
                'image_credit' => '54str · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Puxada triângulo',
                'muscle_group' => 'Costas',
                'equipment' => 'Polia',
                'instructions' => 'Pegada neutra no triângulo, puxe até o peito contraindo as costas.',
                'image_url' => '/exercise-photos/puxador-triangulo.png',
                'image_credit' => 'Franpol · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Remada baixa',
                'muscle_group' => 'Costas',
                'equipment' => 'Polia',
                'instructions' => 'Puxe o cabo em direção ao abdômen mantendo a coluna neutra.',
                'image_url' => '/exercise-photos/remada-baixa.png',
                'image_credit' => 'Franpol · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Remada curvada barra',
                'muscle_group' => 'Costas',
                'equipment' => 'Barra',
                'instructions' => 'Tronco inclinado à frente, puxe a barra em direção ao abdômen.',
                'image_url' => '/exercise-photos/remada-curvada.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Remada aberta máquina',
                'muscle_group' => 'Costas',
                'equipment' => 'Máquina',
                'instructions' => 'Puxe as alavancas em direção ao tronco, mantendo o peito apoiado.',
                'image_url' => '/exercise-photos/remada-maquina.png',
                'image_credit' => 'barry · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Remada unilateral com halter',
                'muscle_group' => 'Costas',
                'equipment' => 'Halteres',
                'instructions' => 'Apoiado no banco, puxe o halter em direção ao quadril de um lado por vez.',
                'image_url' => '/exercise-photos/remada-unilateral-com-halter.png',
                'image_credit' => 'Rottekongen · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Corrida na esteira',
                'muscle_group' => 'Funcional',
                'equipment' => 'Esteira',
                'instructions' => 'Mantenha ritmo constante, postura ereta e passada natural.',
                'image_url' => '/exercise-photos/corrida-na-esteira.jpg',
                'image_credit' => 'Tierrasverdes · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Abdução de quadril na máquina abdutora',
                'muscle_group' => 'Glúteos',
                'equipment' => 'Máquina',
                'instructions' => 'Sentado, afaste as pernas contra a resistência da máquina.',
                'image_url' => '/exercise-photos/abducao-de-quadril-na-maquina.jpg',
                'image_credit' => 'Tierrasverdes · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Cadeira adutora',
                'muscle_group' => 'Glúteos',
                'equipment' => 'Máquina',
                'instructions' => 'Aproxime as pernas contra a resistência, controle a volta.',
                'image_url' => '/exercise-photos/cadeira-adutora.webp',
                'image_credit' => 'flori · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Elevação pélvica com barra',
                'muscle_group' => 'Glúteos',
                'equipment' => 'Barra',
                'instructions' => 'Costas apoiadas no banco, eleve o quadril contraindo os glúteos no topo.',
                'image_url' => '/exercise-photos/elevacao-de-quadril-hip-thrust.webp',
                'image_credit' => 'AlucardEvil40 · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Glúteo no cabo (coice)',
                'muscle_group' => 'Glúteos',
                'equipment' => 'Polia',
                'instructions' => 'Empurre a perna para trás e para cima contraindo o glúteo.',
                'image_url' => '/exercise-photos/gluteo-no-cabo-coice.jpg',
                'image_credit' => 'Tierrasverdes · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Desenvolvimento com halteres',
                'muscle_group' => 'Ombros',
                'equipment' => 'Halteres',
                'instructions' => 'Empurre os halteres para cima até quase estender totalmente os cotovelos.',
                'image_url' => '/exercise-photos/desenvolvimento-com-halteres.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Elevação frontal',
                'muscle_group' => 'Ombros',
                'equipment' => 'Halteres',
                'instructions' => 'Eleve os braços à frente do corpo até a altura dos ombros.',
                'image_url' => '/exercise-photos/elevacao-frontal.png',
                'image_credit' => 'philip · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Elevação lateral',
                'muscle_group' => 'Ombros',
                'equipment' => 'Halteres',
                'instructions' => 'Eleve os braços lateralmente até a altura dos ombros, cotovelos levemente flexionados.',
                'image_url' => '/exercise-photos/elevacao-lateral.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Remada alta com barra',
                'muscle_group' => 'Ombros',
                'equipment' => 'Barra',
                'instructions' => 'Puxe a barra rente ao corpo até a altura do peito, cotovelos acima das mãos.',
                'image_url' => '/exercise-photos/remada-alta.png',
                'image_credit' => 'wger.de · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Panturrilha no leg press',
                'muscle_group' => 'Panturrilha',
                'equipment' => 'Máquina',
                'instructions' => 'Empurre a plataforma apenas com a ponta dos pés, joelhos estendidos.',
                'image_url' => '/exercise-photos/panturrilha-no-leg-press.png',
                'image_credit' => 'nate303303 · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Crossover',
                'muscle_group' => 'Peito',
                'equipment' => 'Polia',
                'instructions' => 'Puxe os cabos em arco até as mãos se encontrarem à frente do corpo.',
                'image_url' => '/exercise-photos/crossover.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Crucifixo reto',
                'muscle_group' => 'Peito',
                'equipment' => 'Halteres',
                'instructions' => 'Braços levemente flexionados, abra e feche em arco como um abraço.',
                'image_url' => '/exercise-photos/crucifixo-reto.png',
                'image_credit' => 'cshep442 · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Flexão de braço',
                'muscle_group' => 'Peito',
                'equipment' => 'Peso corporal',
                'instructions' => 'Corpo alinhado, desça até quase tocar o chão e empurre de volta.',
                'image_url' => '/exercise-photos/flexao-de-braco.png',
                'image_credit' => 'Settebello · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Paralelas (mergulho)',
                'muscle_group' => 'Peito',
                'equipment' => 'Peso corporal',
                'instructions' => 'Desça flexionando os cotovelos, tronco levemente inclinado à frente, e empurre para cima.',
                'image_url' => '/exercise-photos/paralelas-mergulho.png',
                'image_credit' => 'cshep442 · CC0 (wger.de)',
            ],
            [
                'name' => 'Pullover',
                'muscle_group' => 'Peito',
                'equipment' => 'Halteres',
                'instructions' => 'Deitado, leve o halter por trás da cabeça em arco e retorne ao peito.',
                'image_url' => '/exercise-photos/pullover.png',
                'image_credit' => 'Franpol · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Supino reto com halter',
                'muscle_group' => 'Peito',
                'equipment' => 'Halteres',
                'instructions' => 'Halteres alinhados ao peito, empurre para cima até quase travar o cotovelo.',
                'image_url' => '/exercise-photos/supino-com-halteres.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Supino declinado',
                'muscle_group' => 'Peito',
                'equipment' => 'Barra',
                'instructions' => 'Banco declinado, desça a barra até a base do peito controlando o movimento.',
                'image_url' => '/exercise-photos/supino-declinado.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Supino inclinado',
                'muscle_group' => 'Peito',
                'equipment' => 'Barra',
                'instructions' => 'Banco a 30-45°, desça a barra até a parte superior do peito e empurre para cima.',
                'image_url' => '/exercise-photos/supino-inclinado.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Supino máquina',
                'muscle_group' => 'Peito',
                'equipment' => 'Máquina',
                'instructions' => 'Empurre as alavancas à frente mantendo as costas apoiadas no encosto.',
                'image_url' => '/exercise-photos/supino-maquina.webp',
                'image_credit' => 'roneydya · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Supino reto',
                'muscle_group' => 'Peito',
                'equipment' => 'Barra',
                'instructions' => 'Deitado no banco, desça a barra até o peito e empurre até a extensão dos cotovelos.',
                'image_url' => '/exercise-photos/supino-reto.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Avanço alternado',
                'muscle_group' => 'Pernas',
                'equipment' => 'Halteres',
                'instructions' => 'Passo à frente, desça o joelho de trás quase até o chão, mantenha o tronco ereto.',
                'image_url' => '/exercise-photos/afundo.png',
                'image_credit' => 'Franpol · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Agachamento búlgaro',
                'muscle_group' => 'Pernas',
                'equipment' => 'Halteres',
                'instructions' => 'Pé de trás apoiado no banco, desça o joelho da frente controladamente.',
                'image_url' => '/exercise-photos/agachamento-bulgaro.jpg',
                'image_credit' => 'AlucardEvil40 · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Agachamento livre',
                'muscle_group' => 'Pernas',
                'equipment' => 'Barra',
                'instructions' => 'Pés na largura dos ombros, desça controlando o quadril para trás, mantenha o tronco ereto.',
                'image_url' => '/exercise-photos/agachamento-livre.jpg',
                'image_credit' => 'Workout Guru · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Agachamento livre com halteres (goblet squat)',
                'muscle_group' => 'Pernas',
                'equipment' => 'Halter',
                'instructions' => 'Segure o halter junto ao peito e agache mantendo o tronco ereto.',
                'image_url' => '/exercise-photos/agachamento-livre-com-halteres-goblet-squat.jpeg',
                'image_credit' => 'philip · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Agachamento no smith',
                'muscle_group' => 'Pernas',
                'equipment' => 'Máquina',
                'instructions' => 'Barra guiada, desça controlando o quadril como no agachamento livre.',
                'image_url' => '/exercise-photos/agachamento-no-smith.jpg',
                'image_credit' => 'Tierrasverdes · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Cadeira extensora',
                'muscle_group' => 'Pernas',
                'equipment' => 'Máquina',
                'instructions' => 'Estenda o joelho controladamente até quase a extensão completa.',
                'image_url' => '/exercise-photos/cadeira-extensora.png',
                'image_credit' => 'Franpol · CC0 (wger.de)',
            ],
            [
                'name' => 'Hack machine',
                'muscle_group' => 'Pernas',
                'equipment' => 'Máquina',
                'instructions' => 'Costas apoiadas, desça flexionando os joelhos e empurre de volta.',
                'image_url' => '/exercise-photos/hack-machine.webp',
                'image_credit' => 'polloperro · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Passada (walking lunge)',
                'muscle_group' => 'Pernas',
                'equipment' => 'Halteres',
                'instructions' => 'Afundos alternados avançando pelo espaço, sem parar entre as passadas.',
                'image_url' => '/exercise-photos/passada-walking-lunge.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Cadeira flexora',
                'muscle_group' => 'Posterior',
                'equipment' => 'Máquina',
                'instructions' => 'Sentado, flexione os joelhos trazendo os calcanhares para baixo.',
                'image_url' => '/exercise-photos/cadeira-flexora.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Good morning',
                'muscle_group' => 'Posterior',
                'equipment' => 'Barra',
                'instructions' => 'Barra nas costas, incline o tronco à frente mantendo a coluna neutra.',
                'image_url' => '/exercise-photos/good-morning.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Levantamento terra com barra',
                'muscle_group' => 'Posterior',
                'equipment' => 'Barra',
                'instructions' => 'Mantenha a coluna neutra, empurre o chão com os pés, estenda quadril e joelho ao mesmo tempo.',
                'image_url' => '/exercise-photos/levantamento-terra.jpeg',
                'image_credit' => 'philip · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Levantamento terra romeno',
                'muscle_group' => 'Posterior',
                'equipment' => 'Barra',
                'instructions' => 'Quadril para trás com pernas quase estendidas, barra sempre próxima ao corpo.',
                'image_url' => '/exercise-photos/levantamento-terra-romeno.webp',
                'image_credit' => 'AlucardEvil40 · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Mesa flexora',
                'muscle_group' => 'Posterior',
                'equipment' => 'Máquina',
                'instructions' => 'Flexione o joelho trazendo o calcanhar em direção ao glúteo.',
                'image_url' => '/exercise-photos/mesa-flexora.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Stiff',
                'muscle_group' => 'Posterior',
                'equipment' => 'Barra',
                'instructions' => 'Joelhos levemente flexionados, desça a barra rente às pernas até sentir alongar o posterior.',
                'image_url' => '/exercise-photos/stiff.webp',
                'image_credit' => 'AlucardEvil40 · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Encolhimento com halteres',
                'muscle_group' => 'Trapézio',
                'equipment' => 'Halteres',
                'instructions' => 'Eleve os ombros segurando os halteres ao lado do corpo.',
                'image_url' => '/exercise-photos/encolhimento-com-halteres.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Encolhimento de ombros com barra',
                'muscle_group' => 'Trapézio',
                'equipment' => 'Barra',
                'instructions' => 'Eleve os ombros em direção às orelhas sem flexionar os cotovelos.',
                'image_url' => '/exercise-photos/encolhimento-de-ombros-com-barra.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Tríceps unilateral na polia alta',
                'muscle_group' => 'Tríceps',
                'equipment' => 'Polia',
                'instructions' => 'Um braço por vez, estenda o cotovelo mantendo-o próximo ao corpo.',
                'image_url' => '/exercise-photos/extensao-de-triceps-unilateral.png',
                'image_credit' => 'Franpol · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Tríceps banco livre',
                'muscle_group' => 'Tríceps',
                'equipment' => 'Peso corporal',
                'instructions' => 'Mãos no banco atrás do corpo, desça flexionando os cotovelos e empurre de volta.',
                'image_url' => '/exercise-photos/mergulho-no-banco.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
            [
                'name' => 'Tríceps corda',
                'muscle_group' => 'Tríceps',
                'equipment' => 'Polia',
                'instructions' => 'Cotovelos fixos, estenda o antebraço até a extensão completa.',
                'image_url' => '/exercise-photos/triceps-corda.png',
                'image_credit' => 'nishant0712 · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Tríceps francês com anilha',
                'muscle_group' => 'Tríceps',
                'equipment' => 'Halter',
                'instructions' => 'Halter atrás da cabeça, estenda o cotovelo mantendo o braço fixo.',
                'image_url' => '/exercise-photos/triceps-frances.webp',
                'image_credit' => 'Anastasious · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Tríceps pulley barra reta',
                'muscle_group' => 'Tríceps',
                'equipment' => 'Polia',
                'instructions' => 'Cotovelos fixos ao lado do corpo, empurre a barra até a extensão total.',
                'image_url' => '/exercise-photos/triceps-pulley-barra-reta.png',
                'image_credit' => 'cshep442 · CC-BY-SA 4 (wger.de)',
            ],
            [
                'name' => 'Tríceps testa',
                'muscle_group' => 'Tríceps',
                'equipment' => 'Barra W',
                'instructions' => 'Deitado, desça a barra em direção à testa e estenda de volta.',
                'image_url' => '/exercise-photos/triceps-testa.png',
                'image_credit' => 'Everkinetic · CC-BY-SA 3 (wger.de)',
            ],
        ];
    }
}
